__description__ = "Helper package to be used to simplify a wide range of system operations"
__license__ = "Copyright 2021 NXP"
__version__ = "0.9"
__author__ = "Teodora Mihalachi, Ioan-Dan Puslenghea"
__email__ = "teodora.mihalachi@nxp.com, danioan.puslenghea@nxp.com"
