__description__ = "Helper package to be used to simplify a wide range of system operations"
__license__ = "NXP Semiconductors 2021"
__version__ = "0.2"
__author__ = "Teodora Mihalachi, Ioan-Dan Puslenghea"
__email__ = "teodora.mihalachi@nxp.com, danioan.puslenghea@nxp.com"
